### ISSUE TITLE
Add common table groups for faster subscription

### ISSUE THREAD

**Issue by dongitran** [dongitran/UrDBNotify#2]
Add predefined table groups for common business flows to improve user subscription experience.
### Context
Currently, users need to select tables one by one to subscribe to database changes, which is time-consuming.

### Todo

- [ ] Add inline keyboard for common patterns (e.g., Card Creation Flow)
- [ ] Implement auto-subscription for related tables
- [ ] Example for Card Flow: cards, card_token,...
- [ ] Update bot commands documentation
